### ISSUE TITLE
mwlib import error

### ISSUE THREAD

**Issue by Luther24** [projectgus/yamdwe#6]
This is probably not the right place to ask this question. Nonetheless I'm stuck with this error. 

> Traceback (most recent call last):
>   File "./yamdwe.py", line 17, in <module>
>     import mediawiki, dokuwiki
>   File "/home/caoyuan/Desktop/eclipse_ws/yamdwe-master/dokuwiki.py", line 11, in <module>
>     import wikicontent
>   File "/home/caoyuan/Desktop/eclipse_ws/yamdwe-master/wikicontent.py", line 11, in <module>
>     from mwlib.parser import *
> ImportError: No module named mwlib.parser

**Comment by lordofbikes** [comment]
Even if this issue is a bit aged, I had the same recently.
My fault was to run yamdwe.py as sudo, this eliminated the virtual environment I think.
I did so because of permission problems in the dokuwiki target, but running ```sudo ./yamdwe.py``` doesn't solve the problem, it makes it worse, leading into all above described issues.
After setting proper permissions and owner yamdwe.py worked for me.

Armin

**Comment by projectgus** [comment]
Thanks Armin, that's a good catch to have on record - it's easy to forget that 'sudo' leaves the virtualenv.
